<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vantuz.Core\Vantuz.Core.csproj" />
    <Analyzer Include="..\Armatura.Core.Sdk\bin\$(Configuration)\netstandard2.0\Armatura.Core.Sdk.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
  </ItemGroup>
</Project>
