// <auto-generated>
//     Generated by the ResXFileCodeGenerator tool for invariant resource migration.
// </auto-generated>

namespace VantuzLauncher.Properties;

using System.Resources;
using System.Globalization;

/// <summary>
/// Strongly-typed resource class for VantuzLauncher user-visible strings.
/// F_doc: {Resource lookup returns null or wrong culture} E_doc: {Unit test verifies all keys exist in neutral culture}
/// </summary>
public static class Resources
{
    private static readonly ResourceManager _resourceManager = new("VantuzLauncher.Properties.Resources", typeof(Resources).Assembly);

    /// <summary>
    /// ErrorAccessDenied: "Ошибка доступа! Нет прав на запись в рабочую папку..."
    /// </summary>
    public static string ErrorAccessDenied => _resourceManager.GetString("ErrorAccessDenied", CultureInfo.CurrentCulture)!;

    /// <summary>
    /// ErrorAccessDeniedTitle: "Vantuz Launcher — Ошибка доступа"
    /// </summary>
    public static string ErrorAccessDeniedTitle => _resourceManager.GetString("ErrorAccessDeniedTitle", CultureInfo.CurrentCulture)!;

    /// <summary>
    /// ErrorLaunchFailed: "Ошибка запуска:\n{0}\n\nПодробности записаны в:\n{1}"
    /// </summary>
    public static string ErrorLaunchFailed => _resourceManager.GetString("ErrorLaunchFailed", CultureInfo.CurrentCulture)!;

    /// <summary>
    /// ErrorLaunchFailedTitle: "Vantuz Launcher — Ошибка"
    /// </summary>
    public static string ErrorLaunchFailedTitle => _resourceManager.GetString("ErrorLaunchFailedTitle", CultureInfo.CurrentCulture)!;

    /// <summary>
    /// ErrorCriticalTitle: "Vantuz Launcher — Critical Error"
    /// </summary>
    public static string ErrorCriticalTitle => _resourceManager.GetString("ErrorCriticalTitle", CultureInfo.CurrentCulture)!;

    /// <summary>
    /// ErrorMissingConfigTitle: "Vantuz Launcher — Missing Config"
    /// </summary>
    public static string ErrorMissingConfigTitle => _resourceManager.GetString("ErrorMissingConfigTitle", CultureInfo.CurrentCulture)!;
}
