// <auto-generated>
//     Generated for invariant resource migration (AGENT-REC-020).
// </auto-generated>

namespace Vantuz.Plugins.GUI.MinecraftLauncher.Properties;

using System.Resources;
using System.Globalization;

/// <summary>
/// Strongly-typed resource class for MinecraftLauncher GUI user-visible strings.
/// F_doc: {Resource lookup returns null or wrong culture} E_doc: {Unit test verifies all keys exist in neutral culture}
/// </summary>
public static class Resources
{
    private static readonly ResourceManager _resourceManager = new("Vantuz.Plugins.GUI.MinecraftLauncher.Properties.Resources", typeof(Resources).Assembly);

    public static string StatusEnterCredentials => _resourceManager.GetString("StatusEnterCredentials", CultureInfo.CurrentCulture)!;
    public static string HeaderLogin => _resourceManager.GetString("HeaderLogin", CultureInfo.CurrentCulture)!;
    public static string LabelUsername => _resourceManager.GetString("LabelUsername", CultureInfo.CurrentCulture)!;
    public static string LabelPassword => _resourceManager.GetString("LabelPassword", CultureInfo.CurrentCulture)!;
    public static string CheckRememberMe => _resourceManager.GetString("CheckRememberMe", CultureInfo.CurrentCulture)!;
    public static string HeaderSettings => _resourceManager.GetString("HeaderSettings", CultureInfo.CurrentCulture)!;
    public static string LabelRamAllocation => _resourceManager.GetString("LabelRamAllocation", CultureInfo.CurrentCulture)!;
    public static string RamAllocatedFormat => _resourceManager.GetString("RamAllocatedFormat", CultureInfo.CurrentCulture)!;
    public static string ButtonPlay => _resourceManager.GetString("ButtonPlay", CultureInfo.CurrentCulture)!;
    public static string ButtonCancel => _resourceManager.GetString("ButtonCancel", CultureInfo.CurrentCulture)!;
    public static string HeaderStatus => _resourceManager.GetString("HeaderStatus", CultureInfo.CurrentCulture)!;
    public static string StatusPreparing => _resourceManager.GetString("StatusPreparing", CultureInfo.CurrentCulture)!;
    public static string LogEnterCredentials => _resourceManager.GetString("LogEnterCredentials", CultureInfo.CurrentCulture)!;
}
